env:
  global:
    - CC_TEST_REPORTER_ID=0cf6723dc19d455318ad3c8eff2604eb0e6dc79abb35586c9237b897bace5cef
    
language: php

php:
  - '7.2'

install:
  - composer self-update
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make lint test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT